### PR TITLE
fix: simplify geometries for geoFilters based on inclusion

### LINKED ISSUE #616: simplify geometries for geoFilters based on inclusion

### PR DESCRIPTION
**Pull request by QuCMGisaia**
- Fix #616

- Partial fix for gisaia/ARLAS-wui#967
-> Needs gisaia/ARLAS-web-components#975 for the edits

### CODE REVIEW

File: src/contributors/MapContributor.ts [hunk 1]
```diff
@@ -718,7 +709,7 @@ export class MapContributor extends Contributor {
                     });
                 });
             }
-            if (aois && aois.length > 0) {
+            if (aois.length > 0) {
```
Comment (MohamedHamouGisaia) [inline src/contributors/MapContributor.ts:712]: aois?.length ?

File: src/contributors/MapContributor.ts [hunk 2]
```diff
@@ -3784,37 +3757,41 @@ export class MapContributor extends Contributor {
...
+                const coord = f.geometry.coordinates[0];
+                const n = coord[1][1];
+                const w = this.wrap(coord[2][0], -180, 180);
+                const s = coord[0][1];
+                const e = this.wrap(coord[0][0], -180, 180);
+                const box = w + ',' + s + ',' + e + ',' + n;
+                return {f: bboxPolygon([w, s, e, n]), str: box.trim().toLocaleLowerCase()};
+            } else {
+                // Properly orientate features
+                if (!isClockwise(f.geometry.coordinates[0])) {
```
Comment (MohamedHamouGisaia) [inline src/contributors/MapContributor.ts:3778]: could you add a comment mentionning that we don't reverse internal polygons (rings) as they are not supported

File: src/contributors/MapContributor.ts (hunk 1 above)
Comment (QuCMGisaia) [reply src/contributors/MapContributor.ts:712]: aois is defined right above as a list, so it can't be undefined

**Review by MohamedHamouGisaia — APPROVED** [review]

**Review by sebbousquet — APPROVED** [review]
