### PR TITLE
Fix topology rendering bugs

### LINKED ISSUE #295: TOPOLOGY : data is duplicated when precision change

### LINKED ISSUE #296: TOPOMAP: data in cluster mode is not updated after applying a filter

### PR DESCRIPTION
**Pull request by MohamedHamouGisaia**
- fix #295 topo mode : duplicated data when precision changes
- fix #296 cluster mode : data not updated after applying a filter

### CODE REVIEW

File: src/contributors/MapContributor.ts [hunk 1]
```diff
@@ -585,10 +603,10 @@ export class MapContributor extends Contributor {
 
     public switchLayerCluster(style: Style) {
         if (this.strategyEnum[style.geomStrategy].toString() !== this.geomStrategy.toString()) {
+            this.updateData = true;
             this.geomStrategy = style.geomStrategy;
             if (this.isGeoaggregateCluster) {
                 this.geojsondata.features = [];
-                this.updateData = true;
                 this.fetchType = fetchType.geohash;
                 this.maxValueGeoHash = 0;
```
Comment (sebbousquet) [inline src/contributors/MapContributor.ts]: It could be better to use the new function `clearData()`

Comment (MohamedHamouGisaia) [reply src/contributors/MapContributor.ts]: yes, I fix it

Comment (MohamedHamouGisaia) [reply src/contributors/MapContributor.ts]: fixed
